# Дан текст из 22 предложений, в котором говориться про котов.
## необходимо с помощью косинусного расстояния между частотой встречи слов в предложениях, найти наиболее одинаковые по смыслу предложения.

# В данном случае найти предложения, в которых описываются живые коты

In [25]:
fcats=open("cats.txt",'r')
s=fcats.readlines()
sCats=''
i=0
for line in s:
    print i, line
    i+=1
    sCats+=line


0 In comparison to dogs, cats have not undergone major changes during the domestication process.

1 As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.

2 A common interactive use of cat for a single file is to output the content of a file to standard output.

3 Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.

4 In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.

5 The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.

6 Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).

7 However, if the output is piped or redirected, cat is unnecessary.

8 cat with one named file is safer where human error is a conc

In [2]:
sCats=sCats.lower()

In [3]:
import re

# нужно для каждого слова составить количество его вхождений для каждого предложений, получить лист из словарей

## fcats - файл с предложениями
## sCats -строка со всеми предложениями

In [4]:
def Tokenize(string):
    string=string.lower()
    listOfToken=re.split('[^a-z]', string)
    listOfToken=[el for el in listOfToken if el!='']
    return listOfToken

In [29]:
listOfToken=list()

fcats.seek(0)
for line in fcats:
    line=line.lower()
    listOfToken.append(Tokenize(line))
##токенезировали каждое предложение и вложили каждый лист токенов в общий лист.
print listOfToken

[['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organism

# listOfToken - список токенезированных предложений, где i-й индекс соответствует токенам  в i-ом предложении
# listOfAllToken- список всех слов-токенов

In [41]:
listOfAllToken=Tokenize(sCats)
print len(listOfAllToken)
##токенезировали целый текст

484


In [7]:
def NumOfEntering(word,sentenceWords):
    num=0
    for el in sentenceWords:
        if el == word:
            num+=1
    return num

In [37]:
NumOfTokenInSentence=dict()
for sentence in listOfToken:
    for word in sentence:
        
for word in listOfAllToken:
    for sentece in listOfToken:
        NumOfTokenInSentence[word]=NumOfEntering(word,sentence)

in
comparison
to
dogs
cats
have
not
undergone
major
changes
during
the
domestication
process


# NumOfTokenInSentence - словарь списков. [word][i] элемента соответствует количесву вхождений слова word в i-ое предложение

In [107]:
##создаем словарь списков вхождения в каждое предложeние
##каждый элемент словаря должен быть списком размером в количество предложений, в качестве i-го элемента списка
##выступает количество вхождений слова в предложение:
NumOfTokenInSentence=dict()
for word in listOfAllToken:
    NumOfTokenInSentence[word]=[]

for word in listOfAllToken:
    if NumOfTokenInSentence[word]==[]:
        for sentenceInToken in listOfToken:
            NumOfTokenInSentence[word].append(NumOfEntering(word,sentenceInToken))
print len(NumOfTokenInSentence)

254


## построим таблицу:

In [110]:
import pandas as pd

In [111]:
WordFrame=pd.DataFrame()

In [112]:
for word in NumOfTokenInSentence:
    WordFrame[word]=[num for num in NumOfTokenInSentence[word]]

In [113]:
WordFrame

displays  osx  selection  safari  just  developed  over  vermin  domestic  \
0          0    0          0       0     0          0     0       0         0   
1          0    0          0       0     1          0     0       0         0   
2          0    0          0       0     0          0     0       0         0   
3          0    0          0       0     0          0     0       0         0   
4          0    0          1       0     0          0     0       1         0   
5          0    0          0       0     0          0     0       0         0   
6          0    0          0       0     0          0     0       0         1   
7          0    0          0       0     0          0     0       0         0   
8          0    0          0       0     1          0     0       0         0   
9          0    0          0       0     0          0     0       0         0   
10         0    0          0       0     0          0     0       0         0   
11         0    0          0       0     0          0     0       0         0   
12         1    0          0       0     1          0     0       0         0   
13         0    0          0       0     0          0     0       0         0   
14         0    0          0       0     0          0     2       0         0   
15         0    0          0       0     0          0     0       0         0   
16         0    1          0       0     0          1     0       0         0   
17         0    0          0       0     0          0     0       0         0   
18         0    0          0       1     0          0     0       0         0   
19         0    0          0       0     0          0     0       0         0   
20         0    0          0       0     0          0     0       0         0   
21         0    0          0       0     0          0     0       0         0   

    named  ...   switch  without  command  place  allow  time  redirected  \
0       0  ...        0        0        0      0      0     0           0   
1       0  ...        0        0        0      0      0     0           0   
2       0  ...        0        0        0      0      0     0           0   
3       0  ...        0        0        0      0      0     0           0   
4       0  ...        0        0        0      0      0     0           0   
5       0  ...        0        0        0      0      0     0           0   
6       0  ...        0        0        0      0      0     0           0   
7       0  ...        0        0        0      0      0     0           1   
8       1  ...        0        0        0      0      0     0           0   
9       0  ...        0        0        0      0      0     0           0   
10      0  ...        0        0        1      0      0     0           0   
11      0  ...        0        0        1      0      0     0           1   
12      0  ...        0        1        1      0      0     0           0   
13      0  ...        0        0        0      0      0     0           0   
14      0  ...        0        0        0      0      0     0           0   
15      0  ...        0        0        0      0      1     0           0   
16      0  ...        0        0        0      0      0     0           0   
17      0  ...        1        0        0      0      0     0           0   
18      0  ...        0        0        0      0      0     0           0   
19      0  ...        0        0        0      0      0     1           0   
20      0  ...        0        0        0      1      0     0           0   
21      0  ...        0        0        0      0      0     0           0   

    the  typically  left  
0     1          0     0  
1     0          0     0  
2     1          0     0  
3     0          0     0  
4     0          0     0  
5     1          0     0  
6     2          1     0  
7     1          0     0  
8     2          0     0  
9     0          0     1  
10    2          0     0  
11    1          0     0  
12    2          

In [114]:
import numpy as np

In [115]:
a=[]
for word in NumOfTokenInSentence:
    a.append([num for num in NumOfTokenInSentence[word]])

In [120]:
CatArray=np.array(a)
CatArray=CatArray.T

In [122]:
print CatArray
print CatArray.shape

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]
(22L, 254L)


### Найдем косинусное расстояние от предложения в самой первой строке (In comparison to dogs, cats have not undergone...) до всех остальных с помощью функции scipy.spatial.distance.cosine.

In [124]:
from scipy.spatial import distance

In [130]:
i=0
for arrays in CatArray:
    print i, ':' ,distance.cosine(CatArray[0],arrays)
    i+=1
#print distance.cosine(CatArray[0][:1],CatArray[4][:1])

0 : 0.0
1 : 0.9527544408738466
2 : 0.8644738145642124
3 : 0.8951715163278082
4 : 0.7770887149698589
5 : 0.9402385695332803
6 : 0.7327387580875756
7 : 0.9258750683338899
8 : 0.8842724875284311
9 : 0.9055088817476932
10 : 0.8328165362273942
11 : 0.8804771390665607
12 : 0.8396432548525454
13 : 0.8703592552895671
14 : 0.8740118423302576
15 : 0.9442721787424647
16 : 0.8406361854220809
17 : 0.956644501523794
18 : 0.9442721787424647
19 : 0.8885443574849294
20 : 0.8427572744917122
21 : 0.8250364469440588


## Наименьшее косинусное расстояние между 0-вым предложением и остальными в предложенияъ 4 и 6. По предположению в этих предложениях слово cat употребляется в контексте живого существа.


# предположение оказалось верным.